//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citalMedic_desk.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        public byte id { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_cita { get; set; }
        public Nullable<System.TimeSpan> hora_cita { get; set; }
        public Nullable<int> id_medico { get; set; }
        public Nullable<int> id_paciente { get; set; }
    
        public virtual medico medico { get; set; }
        public virtual paciente paciente { get; set; }
    }
}
